// types.ts — shared TypeScript interfaces used by BOTH frontend and backend
// This is the heart of TypeScript — define your data shape once, use everywhere

// ── Enums ──
// Enums are better than plain strings — TypeScript will catch typos at compile time

export enum Priority {
  Low    = "low",
  Medium = "medium",
  High   = "high",
}

export enum Status {
  Todo       = "todo",
  InProgress = "in_progress",
  Done       = "done",
}

// ── Core Task interface ──
export interface Task {
  id:          string;      // unique ID (generated by backend)
  title:       string;      // task title
  description: string;      // optional description
  priority:    Priority;    // low | medium | high
  status:      Status;      // todo | in_progress | done
  dueDate:     string | null; // ISO date string or null
  createdAt:   string;      // ISO date string
  completedAt: string | null; // set when status → done
}

// ── What frontend sends to create a task ──
export interface CreateTaskInput {
  title:       string;
  description: string;
  priority:    Priority;
  dueDate:     string | null;
}

// ── What frontend sends to update a task ──
export interface UpdateTaskInput {
  title?:       string;
  description?: string;
  priority?:    Priority;
  status?:      Status;
  dueDate?:     string | null;
}

// ── Standard API response wrapper ──
// Every backend route returns this shape — frontend always knows what to expect
export interface ApiResponse<T> {
  success: boolean;
  data:    T | null;
  error:   string | null;
}

// ── Dashboard stats shape ──
export interface TaskStats {
  total:       number;
  completed:   number;
  inProgress:  number;
  todo:        number;
  overdue:     number;
  completionRate: number; // 0-100 percentage
  byPriority: {
    high:   number;
    medium: number;
    low:    number;
  };
}